<?php
/**
 * Magento Bridge
 *
 * @author Yireo
 * @package Magento Bridge
 * @copyright Copyright 2009
 * @license Yireo EULA (www.yireo.com)
 * @link http://www.yireo.com
 */
?>

<div class="columns ">

<div class="side-col" id="page:left">
<?php echo $this->getMenu(); ?>
</div>

<div class="main-col" id="content">
<div class="main-col-inner">

<div class="content-header">
<table cellspacing="0">
	<tr>
		<td style="width:100%;"><h3 class="icon-head head-tag"><?php echo $this->getHeader('Joomla! API browse test'); ?></h3></td>
	</tr>
</table>
</div>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('API settings'); ?></h4>
    </div>

    <div class="fieldset ">
        <table cellspacing="5" class="form-list">
            <tr>
                <td width="150"><strong><?php echo $this->__('API URL'); ?></strong></td>
                <td><?php echo Mage::getStoreConfig('magebridge/settings/api_url'); ?></td>
            </tr>
            <tr>
                <td width="150"><strong><?php echo $this->__('API username'); ?></strong></td>
                <td><?php echo Mage::getStoreConfig('magebridge/settings/api_user'); ?></td>
            </tr>
            <tr>
                <td width="150"><strong><?php echo $this->__('API password'); ?></strong></td>
                <td><?php echo Mage::getStoreConfig('magebridge/settings/api_key'); ?></td>
            </tr>
        </table>
    </div>
</div>

<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('API result'); ?></h4>
    </div>

    <div class="fieldset ">
        <table cellspacing="5" class="form-list">
            <tr>
                <td><?php echo $this->getApiResult(); ?></td>
            </tr>
        </table>
    </div>
</div>

</div>
</div>

