<?php
/**
 * Magento Bridge
 *
 * @author Yireo
 * @package Magento Bridge
 * @copyright Copyright 2009
 * @license Yireo EULA (www.yireo.com)
 * @link http://www.yireo.com
 */
?>

<div class="fieldset ">
    <a href="<?php echo Mage::getModel('adminhtml/url')->getUrl('adminhtml/system_config/edit/section/magebridge'); ?>">
        System &gt; Configuration &gt; [SCOPE] &gt; Services &gt; MageBridge
    </a>
</div>
